flags:
  curl:
    new-base: true
extra-package-dbs: []
packages:
- '.'
extra-deps:
- curl-1.3.8
- data-default-0.7.1.1
- data-default-class-0.1.2.0
- data-default-instances-containers-0.0.1
- data-default-instances-dlist-0.0.1
- data-default-instances-old-locale-0.0.1
- dlist-0.8.0.2
- mtl-2.2.1
- old-locale-1.0.0.7
- parsec-3.1.11
- regex-base-0.93.2
- regex-tdfa-1.2.2
- scalpel-0.3.1
- tagsoup-0.14
- text-1.2.2.1
resolver: ghc-7.10.3
