resolver: lts-6.12

packages:
  - '.'
  - location: ./.
  # - location:
  #     git: https://www.github.com/soenkehahn/wai-make-assets
  #     commit: c72a924
  #   extra-dep: true
  - location:
      git: https://www.github.com/mattjbray/elm-export
      commit: 3dfafc7a717003ff4374119ff6f60e5b56868d8f
    extra-dep: True
  - location:
      git: https://www.github.com/mattjbray/servant-elm
      commit: 28cb98a
    extra-dep: True

extra-deps: []

flags: {}

extra-package-dbs: []
